package my.edu.tarc.insurance

import androidx.appcompat.app.AppCompatActivity
import android.os.Bundle
import android.widget.*
import my.edu.tarc.insurance.databinding.ActivityMainBinding

class MainActivity : AppCompatActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)

        // ActivityMainBinding is auto-generated by the binding class
        val binding = ActivityMainBinding.inflate(layoutInflater)

        setContentView(binding.root)

        binding.buttonCalculate.setOnClickListener {
            var basic : Int = 0
            var extra : Int = 0

            var age = binding.spinnerAge.selectedItemPosition
            when (age) {
                0 -> basic = 60
                1 -> basic = 70
                2 -> basic = 90
                3 -> basic = 120
                4 -> basic = 150
                5 -> basic = 150
            }

            var gender = binding.radioGroupGender.checkedRadioButtonId
            if (gender == binding.radioButtonMale.id) {
                // Calculate extra payment for male
                when (age) {
                    0 -> extra = 0
                    1 -> extra = 50
                    2 -> extra = 100
                    3 -> extra = 120
                    4 -> extra = 200
                    5 -> extra = 200
                }
            }

            var smoker = binding.checkBoxSmoker.isChecked
            if (smoker) {
                // Calculate extra payment for smoker
                when (age) {
                    0 -> extra += 0
                    1 -> extra += 100
                    2 -> extra += 150
                    3 -> extra += 200
                    4 -> extra += 250
                    5 -> extra += 300
                }
            }

            val premium = Premium(basic, extra, basic + extra)
            binding.myPremium = premium

        }
        binding.buttonReset.setOnClickListener {
            binding.spinnerAge.setSelection(0)
            binding.radioGroupGender.clearCheck()
            binding.checkBoxSmoker.isChecked = false
            val premium = Premium(0,0,0)
            binding.myPremium = premium
        }
    }
}